export interface PlatformPageDefinition {
  id: string;
  title: string;
  titleKey?: string;
  description: string;
  descriptionKey?: string;
  path: string;
  menuName: string;
  menuNameKey?: string;
  componentKey: string;
  sort: number;
}

export const platformPageDefinitions: PlatformPageDefinition[] = [
  {
    id: "platform-menus",
    title: "菜单管理",
    titleKey: "platform.menuManagement.title",
    description: "维护菜单定义、路由绑定与显示状态。",
    descriptionKey: "platform.menuManagement.subtitle",
    path: "/platform/menus",
    menuName: "菜单管理",
    menuNameKey: "platform.menuManagement.title",
    componentKey: "shell/MenuManagementPage",
    sort: 1,
  },
  {
    id: "platform-params",
    title: "系统参数",
    titleKey: "platform.systemParams.title",
    description: "维护可复用的平台配置项。",
    descriptionKey: "platform.systemParams.subtitle",
    path: "/platform/params",
    menuName: "系统参数",
    menuNameKey: "platform.systemParams.title",
    componentKey: "shell/SystemParamsPage",
    sort: 10,
  },
  {
    id: "platform-dicts",
    title: "字典管理",
    titleKey: "platform.dictManagement.title",
    description: "维护字典类型与字典项配置。",
    descriptionKey: "platform.dictManagement.subtitle",
    path: "/platform/dicts",
    menuName: "字典管理",
    menuNameKey: "platform.dictManagement.title",
    componentKey: "shell/DictManagementPage",
    sort: 4,
  },
  {
    id: "platform-oauth2-clients",
    title: "OAuth2 客户端",
    titleKey: "platform.oauth2ClientManagement.title",
    description: "维护 OAuth2 客户端、授权类型和令牌时效。",
    descriptionKey: "platform.oauth2ClientManagement.subtitle",
    path: "/platform/oauth2-clients",
    menuName: "OAuth2 客户端",
    menuNameKey: "platform.oauth2ClientManagement.title",
    componentKey: "shell/OAuth2ClientManagementPage",
    sort: 5,
  },
  {
    id: "platform-oauth2-accounts",
    title: "OAuth2 账户",
    titleKey: "platform.oauth2AccountManagement.title",
    description: "查看并维护第三方 OAuth2 账户绑定关系。",
    descriptionKey: "platform.oauth2AccountManagement.subtitle",
    path: "/platform/oauth2-accounts",
    menuName: "OAuth2 账户",
    menuNameKey: "platform.oauth2AccountManagement.title",
    componentKey: "shell/OAuth2AccountManagementPage",
    sort: 6,
  },
  {
    id: "platform-notifications",
    title: "站内通知",
    titleKey: "platform.notifications.title",
    description: "查看站内消息并处理未读状态。",
    descriptionKey: "platform.notifications.subtitle",
    path: "/platform/notifications",
    menuName: "站内通知",
    menuNameKey: "platform.notifications.title",
    componentKey: "shell/NotificationsPage",
    sort: 13,
  },
  {
    id: "platform-notify-templates",
    title: "通知模板",
    titleKey: "platform.notifyTemplateManagement.title",
    description: "维护通知模板并支持直接发送测试通知。",
    descriptionKey: "platform.notifyTemplateManagement.subtitle",
    path: "/platform/notify-templates",
    menuName: "通知模板",
    menuNameKey: "platform.notifyTemplateManagement.title",
    componentKey: "shell/NotifyTemplateManagementPage",
    sort: 11,
  },
  {
    id: "platform-notify-records",
    title: "通知记录",
    titleKey: "platform.notifyRecordManagement.title",
    description: "查看通知发送记录、状态与失败原因。",
    descriptionKey: "platform.notifyRecordManagement.subtitle",
    path: "/platform/notify-records",
    menuName: "通知记录",
    menuNameKey: "platform.notifyRecordManagement.title",
    componentKey: "shell/NotifyRecordPage",
    sort: 12,
  },
  {
    id: "platform-access",
    title: "访问映射",
    titleKey: "platform.roleAccess.title",
    description: "查看角色、权限与当前基座菜单路由映射。",
    descriptionKey: "platform.roleAccess.subtitle",
    path: "/platform/access",
    menuName: "访问映射",
    menuNameKey: "platform.roleAccess.title",
    componentKey: "shell/RoleAccessPage",
    sort: 14,
  },
  {
    id: "platform-organizations",
    title: "组织管理",
    titleKey: "platform.organizationManagement.title",
    description: "维护组织层级、负责人和启停状态。",
    descriptionKey: "platform.organizationManagement.subtitle",
    path: "/platform/organizations",
    menuName: "组织管理",
    menuNameKey: "platform.organizationManagement.title",
    componentKey: "shell/OrganizationManagementPage",
    sort: 2,
  },
  {
    id: "platform-users",
    title: "用户管理",
    titleKey: "platform.userManagement.title",
    description: "维护用户账号、角色与组织归属。",
    descriptionKey: "platform.userManagement.subtitle",
    path: "/platform/users",
    menuName: "用户管理",
    menuNameKey: "platform.userManagement.title",
    componentKey: "shell/UserManagementPage",
    sort: 3,
  },
  {
    id: "platform-org-permissions",
    title: "组织权限",
    titleKey: "platform.orgPermission.title",
    description: "为组织直接分配菜单和按钮权限。",
    descriptionKey: "platform.orgPermission.subtitle",
    path: "/platform/org-permissions",
    menuName: "组织权限",
    menuNameKey: "platform.orgPermission.title",
    componentKey: "shell/OrgPermissionPage",
    sort: 7,
  },
  {
    id: "platform-menu-permissions",
    title: "菜单权限",
    titleKey: "platform.menuPermission.title",
    description: "查看并维护菜单资源上的授权关系。",
    descriptionKey: "platform.menuPermission.subtitle",
    path: "/platform/menu-permissions",
    menuName: "菜单权限",
    menuNameKey: "platform.menuPermission.title",
    componentKey: "shell/MenuPermissionPage",
    sort: 8,
  },
  {
    id: "platform-button-permissions",
    title: "按钮权限",
    titleKey: "platform.buttonPermission.title",
    description: "维护按钮资源并管理其授权关系。",
    descriptionKey: "platform.buttonPermission.subtitle",
    path: "/platform/button-permissions",
    menuName: "按钮权限",
    menuNameKey: "platform.buttonPermission.title",
    componentKey: "shell/ButtonPermissionPage",
    sort: 9,
  },
  {
    id: "platform-storage",
    title: "存储中心",
    titleKey: "platform.storage.title",
    description: "上传、预览并管理平台文件资产。",
    descriptionKey: "platform.storage.subtitle",
    path: "/platform/storage",
    menuName: "存储中心",
    menuNameKey: "platform.storage.title",
    componentKey: "shell/StorageCenterPage",
    sort: 15,
  },
];
