declare namespace NodeJS {
  interface ProcessEnv {
    EXPO_PUBLIC_API_BASE_URL?: string;
    EXPO_PUBLIC_AUTH_LOGIN_PATH?: string;
    EXPO_PUBLIC_AUTH_REFRESH_PATH?: string;
    EXPO_PUBLIC_AUTH_LOGOUT_PATH?: string;
    EXPO_PUBLIC_AUTH_CURRENT_USER_PATH?: string;
    EXPO_PUBLIC_STORAGE_UPLOAD_TASK_PATH?: string;
    EXPO_PUBLIC_STORAGE_UPLOAD_SIMPLE_PATH_TEMPLATE?: string;
    EXPO_PUBLIC_STORAGE_UPLOAD_COMPLETE_PATH_TEMPLATE?: string;
    EXPO_PUBLIC_STORAGE_UPLOAD_BIND_PATH_TEMPLATE?: string;
    EXPO_PUBLIC_STORAGE_FILE_DETAIL_PATH_TEMPLATE?: string;
    EXPO_PUBLIC_STORAGE_FILE_CONTENT_PATH_TEMPLATE?: string;
  }
}
